apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: aysgo9y2e-python 
  janus-idp.io/tekton: aysgo9y2e-python
  backstage.io/kubernetes-id: aysgo9y2e-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aysgo9y2e-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml