apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aysgo9y2e-python
  janus-idp.io/tekton: aysgo9y2e-python
  backstage.io/kubernetes-id: aysgo9y2e-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aysgo9y2e-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
