apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aysgo9y2e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aysgo9y2e-python 
  name: aysgo9y2e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aysgo9y2e-python 
